spring:
  application:
    name: ib-demo-story
  profiles:    active:    - dev

ib:
  core:    speed: 1.0
    image-update-frame: 3
  repo:    remote-url: http://localhost:80
  mode:
    story:
      enable: true
      stages:
      - cn.milai.ibdemo.story.UnknownVisitor
      - cn.milai.ibdemo.story.DeepSeaCity  container:
    plugin:      metrics:
        interval: 0        categories:
          physics: true
          aliveCheck: true
          control: true
          metrics: true          ui: true
